name: golangci-lint
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  merge_group:
    types:
      - checks_requested
jobs:
  golangci:
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.21.x']
        os: [ubuntu-latest, windows-latest]
    name: Lint
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.55
        args: --new-from-rev=origin/master --config=.golangci.yml --timeout=25m 
